model:
  model_name: "halfunet"
  model_conf: null
  num_inter_steps: 1
  lr: 1e-4
  loss: "mse"
  training_strategy: "diff_ar"
  use_lr_scheduler: False
  precision: "32"

  no_log: False # doublon avec trainer.logger
  channels_last: False
  save_path: "/scratch/shared/py4cast/logs/test_cli/poesy/halfunet/to_del/"